# Generated by Django 3.0.1 on 2020-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=150)),
                ('kiswahili', models.CharField(max_length=150)),
                ('translatedyes', models.IntegerField(default=0)),
                ('translatedno', models.IntegerField(default=0)),
            ],
        ),
    ]
