# Generated by Django 3.0.1 on 2020-05-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engkis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='translatedno',
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='kiswahili',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
