# Generated by Django 3.0.1 on 2020-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engkis', '0002_auto_20200503_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='word',
            name='kiswahili',
            field=models.CharField(max_length=150),
        ),
    ]
